version: '3.7'

services:
  php:
    build: .
    volumes: 
      - ./nexusphp:/var/www/html

  nginx:
    image: nginx
    volumes:
      - ./nexusphp.conf:/etc/nginx/conf.d/default.conf
      - ./nexusphp:/var/www/html
    ports:
      - 8000:80

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    volumes:
      - ./nexusphp/_db/dbstructure_v1.6.sql:/docker-entrypoint-initdb.d/dbstructure.sql
    environment:
      MYSQL_ROOT_PASSWORD: nexusphp
      MYSQL_DATABASE: nexus_php_php8
      MYSQL_USER: nexusphp
      MYSQL_PASSWORD: nexusphp

  redis:
    image: redis

volumes:
  db_data: